/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.AnAnInfoWebMagic.thrift;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-6-9")
public class ParamsIn implements org.apache.thrift.TBase<ParamsIn, ParamsIn._Fields>, java.io.Serializable, Cloneable, Comparable<ParamsIn> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ParamsIn");

  private static final org.apache.thrift.protocol.TField STR_CMD_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("strCmdID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField JSON_IN_FIELD_DESC = new org.apache.thrift.protocol.TField("jsonIn", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ParamsInStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ParamsInTupleSchemeFactory());
  }

  public String strCmdID; // required
  public String jsonIn; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STR_CMD_ID((short)1, "strCmdID"),
    JSON_IN((short)2, "jsonIn");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STR_CMD_ID
          return STR_CMD_ID;
        case 2: // JSON_IN
          return JSON_IN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STR_CMD_ID, new org.apache.thrift.meta_data.FieldMetaData("strCmdID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.JSON_IN, new org.apache.thrift.meta_data.FieldMetaData("jsonIn", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ParamsIn.class, metaDataMap);
  }

  public ParamsIn() {
  }

  public ParamsIn(
    String strCmdID,
    String jsonIn)
  {
    this();
    this.strCmdID = strCmdID;
    this.jsonIn = jsonIn;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ParamsIn(ParamsIn other) {
    if (other.isSetStrCmdID()) {
      this.strCmdID = other.strCmdID;
    }
    if (other.isSetJsonIn()) {
      this.jsonIn = other.jsonIn;
    }
  }

  public ParamsIn deepCopy() {
    return new ParamsIn(this);
  }

  @Override
  public void clear() {
    this.strCmdID = null;
    this.jsonIn = null;
  }

  public String getStrCmdID() {
    return this.strCmdID;
  }

  public ParamsIn setStrCmdID(String strCmdID) {
    this.strCmdID = strCmdID;
    return this;
  }

  public void unsetStrCmdID() {
    this.strCmdID = null;
  }

  /** Returns true if field strCmdID is set (has been assigned a value) and false otherwise */
  public boolean isSetStrCmdID() {
    return this.strCmdID != null;
  }

  public void setStrCmdIDIsSet(boolean value) {
    if (!value) {
      this.strCmdID = null;
    }
  }

  public String getJsonIn() {
    return this.jsonIn;
  }

  public ParamsIn setJsonIn(String jsonIn) {
    this.jsonIn = jsonIn;
    return this;
  }

  public void unsetJsonIn() {
    this.jsonIn = null;
  }

  /** Returns true if field jsonIn is set (has been assigned a value) and false otherwise */
  public boolean isSetJsonIn() {
    return this.jsonIn != null;
  }

  public void setJsonInIsSet(boolean value) {
    if (!value) {
      this.jsonIn = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STR_CMD_ID:
      if (value == null) {
        unsetStrCmdID();
      } else {
        setStrCmdID((String)value);
      }
      break;

    case JSON_IN:
      if (value == null) {
        unsetJsonIn();
      } else {
        setJsonIn((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STR_CMD_ID:
      return getStrCmdID();

    case JSON_IN:
      return getJsonIn();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STR_CMD_ID:
      return isSetStrCmdID();
    case JSON_IN:
      return isSetJsonIn();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ParamsIn)
      return this.equals((ParamsIn)that);
    return false;
  }

  public boolean equals(ParamsIn that) {
    if (that == null)
      return false;

    boolean this_present_strCmdID = true && this.isSetStrCmdID();
    boolean that_present_strCmdID = true && that.isSetStrCmdID();
    if (this_present_strCmdID || that_present_strCmdID) {
      if (!(this_present_strCmdID && that_present_strCmdID))
        return false;
      if (!this.strCmdID.equals(that.strCmdID))
        return false;
    }

    boolean this_present_jsonIn = true && this.isSetJsonIn();
    boolean that_present_jsonIn = true && that.isSetJsonIn();
    if (this_present_jsonIn || that_present_jsonIn) {
      if (!(this_present_jsonIn && that_present_jsonIn))
        return false;
      if (!this.jsonIn.equals(that.jsonIn))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_strCmdID = true && (isSetStrCmdID());
    list.add(present_strCmdID);
    if (present_strCmdID)
      list.add(strCmdID);

    boolean present_jsonIn = true && (isSetJsonIn());
    list.add(present_jsonIn);
    if (present_jsonIn)
      list.add(jsonIn);

    return list.hashCode();
  }

  @Override
  public int compareTo(ParamsIn other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStrCmdID()).compareTo(other.isSetStrCmdID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStrCmdID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.strCmdID, other.strCmdID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJsonIn()).compareTo(other.isSetJsonIn());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJsonIn()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jsonIn, other.jsonIn);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ParamsIn(");
    boolean first = true;

    sb.append("strCmdID:");
    if (this.strCmdID == null) {
      sb.append("null");
    } else {
      sb.append(this.strCmdID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("jsonIn:");
    if (this.jsonIn == null) {
      sb.append("null");
    } else {
      sb.append(this.jsonIn);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (strCmdID == null) {
      throw new TProtocolException("Required field 'strCmdID' was not present! Struct: " + toString());
    }
    if (jsonIn == null) {
      throw new TProtocolException("Required field 'jsonIn' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ParamsInStandardSchemeFactory implements SchemeFactory {
    public ParamsInStandardScheme getScheme() {
      return new ParamsInStandardScheme();
    }
  }

  private static class ParamsInStandardScheme extends StandardScheme<ParamsIn> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ParamsIn struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // STR_CMD_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.strCmdID = iprot.readString();
              struct.setStrCmdIDIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // JSON_IN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.jsonIn = iprot.readString();
              struct.setJsonInIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ParamsIn struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.strCmdID != null) {
        oprot.writeFieldBegin(STR_CMD_ID_FIELD_DESC);
        oprot.writeString(struct.strCmdID);
        oprot.writeFieldEnd();
      }
      if (struct.jsonIn != null) {
        oprot.writeFieldBegin(JSON_IN_FIELD_DESC);
        oprot.writeString(struct.jsonIn);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ParamsInTupleSchemeFactory implements SchemeFactory {
    public ParamsInTupleScheme getScheme() {
      return new ParamsInTupleScheme();
    }
  }

  private static class ParamsInTupleScheme extends TupleScheme<ParamsIn> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ParamsIn struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.strCmdID);
      oprot.writeString(struct.jsonIn);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ParamsIn struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.strCmdID = iprot.readString();
      struct.setStrCmdIDIsSet(true);
      struct.jsonIn = iprot.readString();
      struct.setJsonInIsSet(true);
    }
  }

}

